apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namePrefix: dev-

nameSuffix: -patch-json-6902

commonLabels:
  layer: patch-json-6902

replicas:
  - name: doctors-directory-client-deployment
    count: 3

patchesJson6902:
  - target:
      kind: Deployment
      name: doctors-directory-client-deployment
    patch: |-
      - op: add
        path: /metadata/labels/addedBy
        value: patches-json-6902-inline
  - target:
      kind: Deployment
      name: doctors-directory-client-deployment
    path: ./patches/patches-json-6902-patch.yaml
