apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namePrefix: dev-

nameSuffix: -patch-json-6902

replicas:
  - count: 3
    name: doctors-directory-client-deployment

labels:
  - includeSelectors: true
    pairs:
      layer: patch-json-6902
patches:
  - patch: |-
      - op: add
        path: /metadata/labels/addedBy
        value: patches-json-6902-inline
    target:
      kind: Deployment
      name: doctors-directory-client-deployment
  - path: ./patches/patches-json-6902-patch.yaml
    target:
      kind: Deployment
      name: doctors-directory-client-deployment
