apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namePrefix: dev-

nameSuffix: -patch-strategic-merge

labels:
  - includeSelectors: true
    pairs:
      layer: patch-strategic-merge
patches:
  - path: ./patches/patches-strategic-merge-patch.yaml
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: doctors-directory-client-deployment
        namespace: doctors-directory
        labels:
          addedThrough: patches-strategic-merge-inline
      spec:
        replicas: 5
        selector:
          matchLabels:
            app: doctors-directory-client
