apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

namePrefix: dev-

nameSuffix: -patch-strategic-merge

commonLabels:
  layer: patch-strategic-merge

patchesStrategicMerge:
  - ./patches/patches-strategic-merge-patch.yaml
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: doctors-directory-client-deployment
      namespace: doctors-directory
      labels:
        addedThrough: patches-strategic-merge-inline
    spec:
      replicas: 5
      selector:
        matchLabels:
          app: doctors-directory-client
