apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

nameSuffix: -patches

commonLabels:
  layer: patches

patches:
  - path: patches-patch.yaml
    target:
      kind: Deployment
      name: doctors-directory-server-deployment
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 8
    target:
      kind: Deployment
      name: doctors-directory-client-deployment
