apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-dev-patches-env
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    directory:
      recurse: false
    repoURL: https://github.com/TluwaniMS/kustomize-practice-project.git
    targetRevision: master
    path: doctors-directory-app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-doctors-directory-patches
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true