apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-dev-patch-json-6902-env
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    directory:
      recurse: false
    repoURL: https://github.com/TluwaniMS/kustomize-practice-project.git
    targetRevision: master
    path: "doctors-directory-app/overlays/dev-patch-json-6902"
  destination:
    server: https://kubernetes.default.svc
    namespace: dev-doctors-directory-patch-json-6902
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true